Metrics/MethodLength: 
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Layout/IndentationWidth:
  Width: 2
  IgnoredPatterns: []

Style/Documentation:
  Enabled: true

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/Next:
  Enabled: false
